load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "misfits",
    main_class = 'AppKt',
    srcs = glob(["**/*.kt"]),
    deps = [
        # "//path/to/dependency",
    ],
)
